# Generated by Django 5.1.7 on 2026-03-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionCasco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'seccion_casco',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionCasco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tomado_por', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('buque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_casco', to='api.buque')),
            ],
            options={
                'db_table': 'inspeccion_casco',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.CharField(max_length=500)),
                ('imagen_anotada', models.CharField(blank=True, max_length=500, null=True)),
                ('detecciones', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ano_construccion', models.IntegerField()),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='vision.inspeccioncasco')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='vision.seccioncasco')),
            ],
            options={
                'db_table': 'foto_inspeccion',
                'ordering': ['fecha_creacion'],
                'indexes': [models.Index(fields=['inspeccion', 'estado'], name='foto_inspec_inspecc_2c6c0d_idx'), models.Index(fields=['seccion'], name='foto_inspec_seccion_2ab076_idx')],
            },
        ),
    ]
