# Generated by Django 5.1.7 on 2025-10-27 09:16

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('autonomia_horas', models.IntegerField(blank=True, null=True)),
                ('vida_diseno_anios', models.IntegerField(blank=True, null=True)),
                ('horas_navegacion_anio', models.IntegerField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('etapa', models.CharField(default='Activo', max_length=255)),
                ('rondas_config', models.JSONField(blank=True, default=dict)),
                ('documentos', models.JSONField(blank=True, default=list)),
                ('vel_maxima_nudos', models.FloatField(blank=True, null=True)),
                ('autonomia_dias', models.IntegerField(blank=True, null=True)),
                ('alcance_nm_a_12kn', models.FloatField(blank=True, null=True)),
                ('eslora_total_m', models.FloatField(blank=True, null=True)),
                ('manga_moldeada_m', models.FloatField(blank=True, null=True)),
                ('puntal_m', models.FloatField(blank=True, null=True)),
                ('calado_diseno_m', models.FloatField(blank=True, null=True)),
                ('desplazamiento_ton', models.FloatField(blank=True, null=True)),
                ('combustible_diario_m3', models.FloatField(blank=True, null=True)),
                ('combustible_diesel_m3', models.FloatField(blank=True, null=True)),
                ('combustible_helicoptero_m3', models.FloatField(blank=True, null=True)),
                ('gasolina_botes_m3', models.FloatField(blank=True, null=True)),
                ('agua_potable_m3', models.FloatField(blank=True, null=True)),
                ('aceite_lubricante_m3', models.FloatField(blank=True, null=True)),
                ('aceite_hidraulico_m3', models.FloatField(blank=True, null=True)),
                ('contexto_operacional', models.JSONField(blank=True, default=dict)),
                ('misiones', models.JSONField(blank=True, default=list)),
                ('grupos_constructivos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buques',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_referencia', models.IntegerField(unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=100)),
                ('valor_maximo', models.FloatField()),
                ('valor_minimo', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parametros',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_referencia', models.IntegerField(unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'sistemas',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_cj', models.CharField(blank=True, help_text='Código CJ específico del equipo (ej: 23311, 23312)', max_length=10, null=True)),
                ('numero_equipo_sap', models.CharField(blank=True, help_text='Número de equipo en sistema SAP', max_length=100, null=True)),
                ('contador', models.IntegerField(blank=True, help_text='Contador del equipo', null=True)),
                ('documentos', models.JSONField(blank=True, default=list)),
                ('placas', models.JSONField(blank=True, default=list)),
                ('parametros_imagenes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.buque')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sistema')),
            ],
            options={
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomado_en', models.DateTimeField(db_column='fecha')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('tomado_por', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.buque')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='api.equipo')),
            ],
            options={
                'db_table': 'ronda',
                'ordering': ['-tomado_en'],
            },
        ),
        migrations.CreateModel(
            name='RondaLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(blank=True, default='', max_length=100)),
                ('valor_minimo', models.FloatField(blank=True, null=True)),
                ('valor_maximo', models.FloatField(blank=True, null=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.parametro')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='api.ronda')),
            ],
            options={
                'db_table': 'ronda_lecturas',
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_referencia', models.IntegerField(unique=True)),
                ('descripcion', models.TextField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
            ],
            options={
                'db_table': 'subgrupos',
            },
        ),
        migrations.AddField(
            model_name='sistema',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subgrupo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subgrupo'),
        ),
        migrations.CreateModel(
            name='Subsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_referencia', models.IntegerField(unique=True)),
                ('descripcion', models.TextField()),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sistema')),
            ],
            options={
                'db_table': 'subsistemas',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='subsistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subsistema'),
        ),
        migrations.CreateModel(
            name='SubsistemaParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parametro')),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subsistema')),
            ],
            options={
                'db_table': 'subsistema_parametros',
            },
        ),
        migrations.CreateModel(
            name='EquipoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parametro')),
            ],
            options={
                'db_table': 'equipo_parametros',
                'unique_together': {('equipo', 'parametro')},
            },
        ),
        migrations.AddIndex(
            model_name='ronda',
            index=models.Index(fields=['equipo', 'tomado_en'], name='ronda_equipo__5f1b61_idx'),
        ),
        migrations.AddIndex(
            model_name='rondalectura',
            index=models.Index(fields=['parametro'], name='ronda_lectu_paramet_a2cef0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rondalectura',
            unique_together={('ronda', 'parametro')},
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['placas'], name='idx_equipos_placas_gin'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['parametros_imagenes'], name='idx_equipos_paramimgs_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='subsistemaparametro',
            unique_together={('subsistema', 'parametro')},
        ),
    ]
